export const CATEGORIES_FETCHED = "gousto@CATEGORIES_FETCHED";
export const CATEGORIES_LOADING= "gousto@CATEGORIES_LOADING";

export const PRODUCTS_FETCHED = "gousto@PRODUCTS_FETCHED";
export const PRODUCTS_LOADING= "gousto@PRODUCTS_LOADING";
